nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-berry.cjs

npmRegistries:
  //registry.npmjs.org/:
    npmAlwaysAuth: true
    npmAuthToken: $NPM_CONFIG_TOKEN

npmScopes:
  subsystem:
    npmRegistryServer: "https://registry.npmjs.org/"